### ISSUE TITLE
Server Configuration Syncing issues

### ISSUE THREAD

**Issue by MistakingManx** [Fuzss/fivefeetsmall#90] opened 2022-05-14 17:40 UTC
If your client-side config and the server-side config are different, you can't join the server because the mod removes the entries for those blocks.

Extremely noticeable with Bubble Columns and Sea Grass being disabled / enabled.

**Comment by embeddedt** [comment] 2022-05-14 17:41
This is intended behavior; you should keep the configs synchronized unless you have a very good reason not to.

**Comment by MistakingManx** [comment] 2022-05-14 17:42
I can't really control other people's configs, bubble columns are disabled by default.

**Comment by embeddedt** [comment] 2022-05-14 17:44
Unfortunately, the way Forge works, you will have to supply them a config file (e.g. as part of a modpack). Even if I wanted to support server->client synchronization, I am not sure I can take blocks in and out of the registry at runtime.

**Comment by MistakingManx** [comment] 2022-05-14 17:48
Oh, toggling the option for Bubble Columns works without restarting the game, I had to test it, it might even work without leaving the world, though it acted kind of buggy when I did that.

**Comment by embeddedt** [comment] 2022-05-14 17:50
I would strongly advise that you don't try changing settings at runtime; there are a lot of things that are very likely to go wrong if you do that.

**Comment by MistakingManx** [comment] 2022-05-14 18:04
It seemed to work fine.. you could test it yourself if you're curious

**Comment by embeddedt** [comment] 2022-05-14 22:15
Interesting. If it works for you that's good, but I don't understand why or how it does work. :laughing: In any case, I'm going to close this as the original report is not a bug.

**Closed as completed by embeddedt** 2022-05-14 22:15 UTC
