### ISSUE TITLE
[SUGGESTION] Witchery: Resurrected integration

### ISSUE THREAD

**Issue by Shazuli** [Fuzss/fivefeetsmall#82] opened 2022-03-24 14:17 UTC
***Hi***

It would be neat if sneaking behavior became disabled if [Witchery: Resurrected](https://witchery.msrandom.net) mod installed and is currently a wolf transformation. When you are in wolf form the player should just be 1 block tall, but the camera forces 2 block tall perspective, making the camera clip through blocks when walking under 1 block tall tunnels.

**Comment by embeddedt** [comment] 2022-03-24 14:24
Duplicate of #81. Please see my reasoning there.

**Closed as completed by embeddedt** 2022-03-24 14:24 UTC

**Comment by Shazuli** [comment] 2022-03-25 09:11
@embeddedt 

This is what works for me. I couldn't get your project to compile (Maven can't find any of the dependencies for some reason) so I can't test if it works. It does work in another mod however.
```java
import net.minecraft.entity.player.EntityPlayer;
import net.minecraftforge.fml.common.Loader;
import net.msrandom.witchery.WitcheryResurrected;
import net.msrandom.witchery.init.WitcheryCreatureTraits;
import net.msrandom.witchery.init.data.WitcheryAlternateForms;
import net.msrandom.witchery.transformation.CreatureForm;
import net.msrandom.witchery.util.WitcheryUtils;

public class WitcheryTransformations
{
    public static boolean isWerewolf(EntityPlayer player)
    {
        return Loader.isModLoaded(WitcheryResurrected.MOD_ID) &&
                WitcheryUtils.getExtension(player).isTransformation(WitcheryCreatureTraits.WEREWOLF);
    }

    public static boolean isWolfTransformation(EntityPlayer player)
    {
        return isWerewolf(player) &&
                WitcheryUtils.getExtension(player).getCurrentForm() == WitcheryAlternateForms.WOLF;
    }

    public static boolean isWolfmanTransformation(EntityPlayer player)
    {
        return isWerewolf(player) &&
                WitcheryUtils.getExtension(player).getCurrentForm() == WitcheryAlternateForms.WOLFMAN;
    }
}
```

**Comment by embeddedt** [comment] 2022-03-25 12:34
> I couldn't get your project to compile (Maven can't find any of the dependencies for some reason) 

This should be fixed now if you pull the branch again. I forgot to apply a fix from another branch.

**Comment by Shazuli** [comment] 2022-03-25 15:22
Still no luck:
```
./gradlew
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.10.3/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :
This mapping 'stable_39' was designed for MC 1.12! Use at your own peril.
#################################################
         ForgeGradle 2.3-1.0.5-87a5c157        
   https://github.com/anatawa12/ForgeGradle-2.3  
#################################################
                 Powered by MCP                  
             http://modcoderpack.com             
     by: Searge, ProfMobius, R4wk, ZeuX          
     Fesh0r, IngisKahn, bspkrs, LexManos         
#################################################

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'AquaAcrobatics'.
> Could not resolve all dependencies for configuration ':deobfProvided'.
   > Could not resolve curse.maven:artemislib-313590:2741812.
     Required by:
         project :
      > Skipped due to earlier error
   > Could not resolve curse.maven:betweenlands-243363:3540284.
     Required by:
         project :
      > Skipped due to earlier error
   > Could not resolve curse.maven:chiseledme-250075:3467731.
     Required by:
         project :
      > Skipped due to earlier error
   > Could not resolve curse.maven:dynamictrees-252818:3446235.
     Required by:
         project :
      > Skipped due to earlier error
   > Could not resolve curse.maven:endercore-231868:2972849.
     Required by:
         project :
      > Skipped due to earlier error
   > Could not resolve curse.maven:enderio-64578:3328811.

...

> Skipped due to earlier error
   > Could not resolve curse.maven:xaerosminimap-263420:3630494.
     Required by:
         project :
      > Skipped due to earlier error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 17s
```

**Comment by embeddedt** [comment] 2022-03-25 15:57
Gradle caching is really aggressive sometimes... try `./gradlew --refresh-dependencies build`? CI uses a fresh environment each time and succeeded after my fix, so it must be your local cache.
