### ISSUE TITLE
Shift+Rightclick interactions in flight are broken

### ISSUE THREAD

**Issue by SteaSteaStea** [Fuzss/fivefeetsmall#115] opened 2023-03-25 01:14 UTC
Shift+Rightclick interactions are bugged if the player is flying (creative mode flight of any kind even vanilla). The simplest example is architecturecraft's roof blocks (slopes). They use shift to determine the orientation like vanilla stairs except they can be placed sideways too. With AA installed the player doesn't visually sneak while using shift in flight (which I actually really like aesthetically) however this seems to cause a desync when placing blocks that follow these placement rules. Another person has come across this issue while placing Mekanism lasers as well.

Example with architecturecraft (seems to apply to other mod/situation as well):

 Placing a roof tile while flying and holding shift places it wrong.  After updating the block by placing another one next to it it snaps to the expected position.
![image](https://user-images.githubusercontent.com/76264934/227674815-6ccae17d-0603-431f-8501-9bfb2e38d5c7.png)

Not sure how much of a problem it would be to fix this. It would be nice to at least have a config option to turn off the sneak changes to at least ensure compatibility.

Mods to replicate issue:

AquaAcrobatics-1.15.2.jar
!mixinbooter-7.0.jar
_MixinBootstrap-1.1.0
architecturecraft-1.12-3.108.jar

**Comment by embeddedt** [comment] 2023-04-18 02:10
Should be fixed in 1.15.3; thanks for this investigation. This turned out to also be the cause of another issue (#117) and the cause of that would have been near-impossible to find if not for you noticing the sneak desync in the first place.

**Closed as completed by embeddedt** 2023-04-18 02:10 UTC
Labels: bug
