### ISSUE TITLE
Issue with Galacticraft

### ISSUE THREAD

**Issue by ghost** [Fuzss/fivefeetsmall#30] opened 2021-05-15 10:11 UTC
There seems to be a compatibility problem with Galacticraft. When adding Galacticraft, it is impossible to sneak and go under a slab. This becomes like an "xray" bug.

I use MixinBootstrap, the latest version of Aqua Acrobatics, the latest version of Galacticraft and the latest version of Forge for 1.12.2.

![2021-05-15_12 08 44](https://user-images.githubusercontent.com/84226714/118356613-62020500-b576-11eb-8888-c8a84cc9fc09.png)
![2021-05-15_12 04 42](https://user-images.githubusercontent.com/84226714/118356615-63333200-b576-11eb-906f-c7c0685bc40e.png)
![2021-05-15_12 04 56](https://user-images.githubusercontent.com/84226714/118356616-64645f00-b576-11eb-9cb4-bd1a3395a825.png)

**Comment by v1993** [comment] 2021-11-14 17:33
This is fixed by using Player API mod.

**Comment by v1993** [comment] 2021-11-27 18:33
Update: Player API from original project causes issues with GalactiCraft, while updated versions lead to Mixin-related crash with Aqua Acrobatics.

[latest.log](https://github.com/Fuzss/aquaacrobatics/files/7612250/latest.log)

**Comment by Fuzss** [comment] 2021-12-01 07:58
Can you link this updated Player API version?

**Comment by v1993** [comment] 2021-12-02 13:02
Here it is: https://www.curseforge.com/minecraft/mc-mods/playerapi

**Comment by embeddedt** [comment] 2021-12-24 18:15
The issue is caused by the fact that both Galacticraft and Player API attempt to overwrite the vanilla player implementation with their own, whereas Aqua Acrobatics just augments the existing implementation using mixins (which is less invasive).

Compatibility with Player API will be difficult to add as it seems to replace *everything* from vanilla (this is the reason for the crash). However, doing the same augmentation to Galacticraft should be feasible.

I've published an experimental version of Aqua Acrobatics [here](https://github.com/Fuzss/aquaacrobatics/actions/runs/1619896998) that does exactly that. You will also need [MixinBooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter) installed for the mixins that target Galacticraft to be enabled.

Please ensure that Player API is **not** installed, otherwise Aqua Acrobatics will crash.

If someone who plays with Galacticraft regularly can give this a try and see what it breaks, it would be appreciated! :slightly_smiling_face:

**Comment by v1993** [comment] 2021-12-24 18:33
Do I have to remove PlayerAPI when testing that build? I'll give it a spin.

**Comment by embeddedt** [comment] 2021-12-24 18:36
Yes. Player API is too invasive and breaks all of the mixins, unfortunately. The concept is good, but doesn't work too well with this mod.

**Comment by v1993** [comment] 2022-02-06 19:05
Just tried out latest CurseForge version - GC integration seems to work fine from limited tests I did. I can't place a slab right above my head while sneaking, but I'm not sure if that's related to this.

**Comment by embeddedt** [comment] 2022-02-20 21:52
> GC integration seems to work fine from limited tests I did. 

Great! Let me know if there are any other issues you encounter.

> I can't place a slab right above my head while sneaking, but I'm not sure if that's related to this.

No, that happens without Galacticraft installed as well. I tried tracking it down, but there's something about 1.12's block placement algorithm that still considers the player to be 2 blocks tall, and honestly, I don't know if it's worth the effort to fix such a niche problem. Thanks for mentioning it, though.

**Closed as completed by embeddedt** 2022-02-20 21:52 UTC
Labels: bug, help wanted
