### ISSUE TITLE
Crash on joining world on 1.11.1

### ISSUE THREAD

**Issue by juraj-hrivnak** [Fuzss/fivefeetsmall#73] opened 2022-02-11 21:04 UTC
### The issue
The game crashed after joining an already existing world with AquaAcrobatics-1.11.1 installed.
Logs say that the Somnia mod causes the issue, but the game crash only when the version of Aqua Acrobatics is higher than 1.9.2 or 1.10.0.

### Logs
[**Full log**](https://github.com/Fuzss/aquaacrobatics/files/8051581/2022-02-11-1.log)
[**Crash log**](https://github.com/Fuzss/aquaacrobatics/files/8051596/crash-2022-02-11_21.45.09-client.txt)

**Comment by embeddedt** [comment] 2022-02-12 00:49
I am not able to reproduce this with 1.11.1 by itself or in my private modpack which contains a lot of common mods. As you noted, the crash itself seems to be unrelated to Aqua Acrobatics (perhaps it triggers a bug in another mod?).

If you can narrow this down to a certain combination of mods, it will be easier to troubleshoot.

**Comment by juraj-hrivnak** [comment] 2022-02-12 01:02
It seems to be related to [Somnia Awoken](https://www.curseforge.com/minecraft/mc-mods/somnia) mod. But until 1.11.1 these mods worked fine together.

**Comment by embeddedt** [comment] 2022-02-12 01:04
I tried running it alongside the Somnia mod (version 1.10.2) and it also runs without crashing, unfortunately.

I assume for you the crash goes away if you remove Somnia?

**Comment by juraj-hrivnak** [comment] 2022-02-12 01:09
Hmm, sorry then. I need to investigate it further. I will have time for it tomorrow.
(I didn’t tried removing Somnia, because it takes so much time to boot my pack. I will need to do a binary search).

**Comment by embeddedt** [comment] 2022-02-12 01:10
No problem! I wish I could be of more help, but unfortunately my PC is probably even slower than yours at starting modpacks. There was a potential crash issue in 1.11.0 but it should have been resolved in this version, and it's very strange that there are no Aqua Acrobatics-related errors in the logs.

**Comment by embeddedt** [comment] 2022-02-13 02:24
There was a fix to an unrelated issue in 1.11.3, but it's possible it may have been the root cause of your crash here. You might want to give that version a try.

**Comment by juraj-hrivnak** [comment] 2022-02-13 22:06
Ok, I just tested the 1.11.3 and now the game freezes instead of crashes on joining the world. Here is the log:
[latest.log](https://github.com/Fuzss/aquaacrobatics/files/8056766/latest.log)

Does it look like it's related to the new get sprites mixin? (I will test it with just only Jurney Map and others.)

**Comment by embeddedt** [comment] 2022-02-13 22:11
This looks a lot more solvable. What version of JourneyMap are you using? My mixin targets the very last 1.12 version, as I assumed that's what everyone uses nowadays.

**Comment by juraj-hrivnak** [comment] 2022-02-13 22:13
I use `journeymap-1.12.2-5.5.4` because that is the only version that supports Journey Map Stages.

**Comment by embeddedt** [comment] 2022-02-13 22:15
Okay, I'll add support for the 5.5 series. Here's a quick hack that should disable that mixin for now:

[1.11.4.zip](https://github.com/Fuzss/aquaacrobatics/files/8056779/1.11.4.zip)

**Comment by juraj-hrivnak** [comment] 2022-02-13 22:18
Okay wow, that was quick! Gimme 10 minutes to boot the pack! 😛

**Comment by juraj-hrivnak** [comment] 2022-02-13 22:30
Oh yeah, that was it! Thank you for fixing it and being so active. I appreciate it.
No crashes or freezes in 1.11.4.

**Closed as completed** 2022-02-13 23:26 UTC
Labels: bug

**Comment by embeddedt** [comment] 2022-02-14 14:15
Proper support for JourneyMap 5.5 is available in 1.11.6.
