### ISSUE TITLE
[BUG] Bubble colums not functioning after new FluidLogged API update

### ISSUE THREAD

**Issue by Carvercarver1** [Fuzss/fivefeetsmall#79] opened 2022-03-19 13:55 UTC
It could be using old classes atm, so update to the newest one needs to be done, or some sort of communication to fluidlog the bubble columns by default in config. 

I will double that on their side as well.

**Comment by embeddedt** [comment] 2022-03-19 23:58
This was caused by updating my MCP mappings, not Fluidlogged, but thanks! Fixed in 1.12.1.

**Closed as completed by embeddedt** 2022-03-19 23:58 UTC
